---
title: "overview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(jsonlite)
library(scales)

responses <- fromJSON("../data/form_responses.json")

responses_race <- responses %>% 
  separate(categories, sep = "; ", into = c("category1", "category2", "category3")) %>% 
  gather(category_num, category, category1:category3) %>% 
  filter(!is.na(category))

responses_ec <- responses %>% 
  separate(extracurriculars, sep = ", ", into = c("ec1", "ec2", "ec3", "ec4", "ec5", "ec6", "ec7", "ec8")) %>% 
  gather(extracurricular_num, extracurricular, ec1:ec8) %>% 
  filter(!is.na(extracurricular)) %>% 
  group_by(extracurricular) %>% 
  filter(n() > 10) %>% 
  ungroup()

responses_q <- responses %>%
  select(starts_with("q_")) %>% 
  filter(q_fossil_fuels_divest != "")
```

## All questions

```{r}
q_stats <- responses_q %>% 
  gather(question, answer, starts_with("q_")) %>% 
  count(question, answer) %>% 
  group_by(question) %>% 
  mutate(pct = n / sum(n)) %>% 
  ungroup() %>% 
  mutate(pct_label = percent(pct, accuracy = 2))
q_stats %>% 
  ggplot(aes(answer, pct, fill = answer)) +
  geom_col() +
  geom_text(aes(label = pct_label), vjust = 0) +
  coord_flip() +
  facet_grid(~ question) +
  scale_x_discrete(limits = c("Neutral", "Strongly disagree", "Disagree", "Agree", "Strongly agree")) +
  scale_fill_manual(values = c("#f8b5a6", "#a87b89", "#c0cccc", "#f8b5a6", "#a87b89")) +
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_blank(),
    plot.background = element_blank(),
    axis.title = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "none",
  )
```

```{r}
ggsave('export.pdf')
```

## Affirmative action

Support for affirmative action among Asians and whites peaks don't show too strongly of a trend , but it seems that higher-income students tend to not support affirmative action. But
```{r}
responses_race %>% 
  group_by(income, category) %>% 
  # filter(n() > 5) %>% 
  ungroup() %>% 
  ggplot(aes(income, fill = affirmative_action)) +
  geom_bar(position = "fill") +
  coord_flip()
  facet_grid(category ~ .)
```

## Free speech

```{r}
responses %>% 
  ggplot(aes(free_speech)) +
  geom_bar() +
  coord_flip()
```

## Eliminate loans

```{r}
responses %>% 
  ggplot(aes(eliminate_loans, ..count.. / sum(..count..))) +
  geom_bar() +
  coord_flip()
```

## Fossil fuels

```{r}
responses %>% 
  ggplot(aes(fossil_fuels_divest)) +
  geom_bar() +
  coord_flip()
me```

## Manhattanville

```{r}
responses %>% 
  ggplot(aes(manhattanville)) +
  geom_bar()
```


